<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.dao.support.DataAccessUtilsTests" tests="10" skipped="0" failures="0" errors="0" timestamp="2021-03-04T16:39:31" hostname="WIN-LQAMLJ4MN5U" time="0.754">
  <properties/>
  <testcase name="withString()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.01"/>
  <testcase name="withInteger()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.507"/>
  <testcase name="exceptionTranslationWithNoTranslation()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.001"/>
  <testcase name="withDate()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.028"/>
  <testcase name="withLong()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.001"/>
  <testcase name="withTooLargeCollection()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.009"/>
  <testcase name="withSameIntegerInstanceTwice()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.003"/>
  <testcase name="withEmptyCollection()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.016"/>
  <testcase name="withEquivalentIntegerInstanceTwice()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.001"/>
  <testcase name="exceptionTranslationWithTranslation()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.015"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
